# config.toml の内容
baseURL = "https://aoiro-labo.com"  # 開発中はlocalhostでOK
languageCode = "ja"
title = "備忘録的なもの｜aoiro-labo"
theme = "aoiro-labo"

[params]
  mainSections = ["posts"] # リスト表示するコンテンツタイプ

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "記事一覧"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30