baseURL = "https://aoiro-labo.com"
languageCode = "ja"
title = "aoiro-labo"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  title = "aoiro-labo"
  description = "備忘録的な何か"
  author = "aoiro"
  
  # Visual & Function Settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  
  # List Settings
  disableSpecial1stPost = false
  displayFullLangName = false
  
  # Theme
  defaultTheme = "auto"
  disableThemeToggle = false

  # Profile Mode
  [params.profileMode]
    enabled = false
    title = "aoiro-labo"
    subtitle = "放送とアニメとバーチャルを愛する特殊なオタク。趣味雑多、広く浅く時々深く。DTV/VTuber/Anime/カラオケ/公共放送 他。"
    imageUrl = "https://pbs.twimg.com/profile_images/1797893047242407936/k-pXm8xZ_400x400.jpg"
    imageTitle = "aoiro"
    imageWidth = 120
    imageHeight = 120
    
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts"
    [[params.profileMode.buttons]]
      name = "Tags"
      url = "/tags"

  # Social Icons
  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/aoiro_labo"
  [[params.socialIcons]]
    name = "note"
    url = "https://note.com/aoiro_labo"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/aoir-labo"

  # Cover Image
  [params.cover]
    responsiveImages = true
    linkFullImages = true
    hidden = false 

  # Search (Fuse.js)
  [params.fuseConfig]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 1
    keys = ["title", "permalink", "summary", "content"]

    [params.editPost]
        URL = "[https://github.com/](https://github.com/)aoiro-labo/aoiro_labo.com/tree/main/content"
        Text = "Suggest Changes"
        appendFilePath = true


[menu]
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 5
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 20

[markup]
  [markup.highlight]
    noClasses = false
    style = "github-dark"